---
version: '3'
services:
  security:
    image: wluisaraujo/nginx
    hostname: balancer.dexter.com.br
    container_name: balancer
    dns_search: balancer.dexter.com.br
    restart: always
    ports:
      - "80/tcp:80/tcp"
      - "443/tcp:443/tcp"
    expose:
      - "80/udp"
      - "443/tcp"
    extra_hosts:
      - "balancer.dexter.com.br:172.16.238.1"  
      - "intranet.dexter.com.br:172.16.238.2"  
      - "ldap.dexter.com.br:172.16.238.3"  
      - "ns1.dexter.com.br:172.16.238.4"  
      - "proxy.dexter.com.br:172.16.238.5"
...
